version: '3.8'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mockserver

  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.11.2
    ports:
      - "1080:1080"
    volumes:
      - ./mockserver/initializerJson.json:/config/initializerJson.json
